/**
 * Main entry point: schema, queries, and types. Deliberately **without driver**.
 *
 * `openDatabase` lives in `@panoma/db/client` because it drags PGlite, which is a WASM module. Any
 * packer that sees it tries to put it in the bundle and breaks it (it replaces the global `URL`
 * and `fs.readFile` stops recognizing its own). By separating it, the web can import queries and
 * types normally and load the driver only at runtime.
 */
export type { Database } from "./client";
export * from "./apps";
export { ingestPortfolio, idFor, pruneSnapshots, SNAPSHOTS_PER_PROJECT } from "./ingest";
export type { IngestResult, IngestPayload, SerializedFamily } from "./ingest";
export { queueWrite } from "./queue";
export {
  listProjects,
  getProject,
  getProjectIcon,
  getProjectLocation,
  listFamilies,
  listPackages,
  listUnsavedWork,
  listDiskUsage,
  getDiskTotals,
  listProjectRoots,
  getDailyReport,
  saveDiskUsage,
  saveAiSummary,
  saveMdReview,
  saveProjectAccounts,
  getOpenContext,
  saveOpenPlan,
  saveBuildCheck,
  setHidden,
  excludeProject,
  forgetProjectsUnder,
  unexcludeProject,
  listHidden,
  getStats,
  stateOf,
  DORMANT_DAYS,
  IDLE_DAYS,
  saveNorth,
  getNorth,
  tasteScore,
  briefScore,
  saveModelCall,
  modelSpendToday,
  saveReview,
  getReview,
  neverReviewed,
  saveLook,
  listLooks,
  getLook,
  projectByIdentity,
  lookedAt,
  autoLooksToday,
  modelSpendByKind,
  modelSpendByModel,
  listModelCalls,
  beliefChurn,
  saveSynthesisPass,
  lastSynthesisHash,
  latestSynthesisByTopic,
  startOfMonthsAgo,
  monthOf,
  startOfDay,
  citedVerdictIds,
  corpusProgress,
  MIN_DISTILL_CITATIONS,
  tasteReach,
  markVerdictsDistilled,
  readVerdictIds,
  remapObservations,
  saveVerdicts,
  listVerdicts,
  deleteVerdicts,
  projectNamesByIdentity,
  saveObservations,
  listObservations,
  observationsByIds,
  observationTopics,
  setObservationTopics,
  insertBeliefs,
  updateBelief,
  listBeliefs,
  signBelief,
  signBeliefByRevision,
  vetoBelief,
  vetoBeliefByRevision,
  retireBeliefs,
  setBeliefScope,
  setBeliefScopeByRevision,
  setBeliefTopics,
  markPublished,
  resolveProposal,
  resolveProposalByRevision,
  standsUp,
  ALIVE,
  SUPPORT_FLOOR,
  inTransaction,
  saveDesignFingerprint,
  getDesignFingerprint,
  portfolioDesign,
  familia,
  esquina,
} from "./queries";
export type {
  ProjectAccount,
  BuildCheckVerdict,
  ProjectCard,
  ProjectState,
  FamilyView,
  PortfolioStats,
  PackageRow,
  UnsavedProject,
  DiskRow,
  DiskTotals,
  HiddenView,
  DailyReport,
  DailyProject,
  DailyCritic,
  DailyProposal,
  DailyCommit,
  DirectorProject,
  TasteScore,
  BriefScore,
  TasteReach,
  PortfolioDesign,
  DesignShare,
  NewVerdict,
  Verdict,
  TasteCitation,
  NewObservation,
  ObservationRow,
  TopicCount,
  BeliefState,
  BeliefCitation,
  BeliefSupport,
  NewBelief,
  BeliefRow,
  PublishedLine,
  NewModelCall,
  ModelSpend,
  KindSpend,
  ModelSpendRow,
  ModelCallRow,
  ChurnMonth,
  SynthesisPass,
  VerdictsSaved,
  CorpusProgress,
  StoredCritique,
  ReviewRow,
  StoredFinding,
  LookFired,
  NewLook,
  LookRow,
} from "./queries";
export {
  createAgent,
  deleteAgent,
  rotateAgentKey,
  authenticateAgent,
  resolveProject,
  getAgentContext,
  openSession,
  closeSession,
  logActivity,
  LOG_SUMMARY_MAX,
  LOG_DETAILS_MAX,
  createTask,
  getTask,
  taskById,
  sessionsOf,
  activitiesOfSessions,
  assignedFindings,
  assignedCritiques,
  discardedCritiques,
  discardedFindings,
  discardTask,
  listProjectLaunches,
  recordLaunch,
  launchedTasks,
  claimTask,
  completeTask,
  listProjectActivity,
  searchJournal,
  searchJournalPage,
  readJournalEntry,
  listProjectTasks,
  listAllActivity,
  listAgents,
  newId,
} from "./agents";
export type { AgentContext, CreatedAgent, JournalHit, JournalPage, JournalEntryPage, NewLaunch } from "./agents";
export {
  NOTE_BUDGET,
  NOTE_MAX,
  NOTE_PENDING_MAX,
  NOTE_SLEEPING_MAX,
  addHumanNote,
  decideNote,
  listProjectNotes,
  noteUsage,
  proposeNote,
  challengeNote,
  listSentinels,
  notesAt,
  recordServing,
  scaleReport,
  setSentinels,
  setValidUntil,
  bridgeCounts,
  triggerMatches,
  validMemoryPath,
  validTrigger,
} from "./notes";
export type { Challenge, ChallengedCheck, NoteDecision, NoteRefusal, ProjectNote, ScaleReport, Sentinel } from "./notes";
export {
  CONSULT_MAX,
  CONSULT_PENDING_MAX,
  STALE_MAX_DAYS,
  doubleReport,
  draftConsultation,
  labelConsultation,
  listProjectConsultations,
  pendingConsultations,
  recordConsultation,
  staleDrafting,
  draftingConsultation,
} from "./consultations";
export type { Consultation, DoubleReport } from "./consultations";
export {
  EPISODE_FIELDS,
  DecisionEpisodeConflict,
  saveNarratives,
  listNarratives,
  narrativesByIds,
  narrativeCount,
  deleteNarratives,
  markNarrativesRead,
  markNarrativesFailed,
  saveDecisionEpisodes,
  listDecisionEpisodes,
  listConflictingEpisodeFamilies,
  decisionEpisodeById,
  decisionEpisodeCount,
  activeEpisodeRevisions,
  activeSuccessor,
  setDecisionEpisodeStatus,
  setDecisionEpisodeValidUntil,
  setDecisionEpisodePredicates,
} from "./episodes";
export type {
  EpisodeFieldName,
  EpisodeFields,
  NewNarrative,
  Narrative,
  NewDecisionEpisode,
  DecisionEpisode,
  EpisodePosition,
} from "./episodes";
export {
  MEMORY_JOB_MAX_ATTEMPTS,
  MEMORY_JOB_LEASE_MS,
  MEMORY_SESSION_WINDOW,
  MEMORY_JOB_STAGED_MAX_BYTES,
  MEMORY_JOB_MAX_INTERVALS,
  MEMORY_JOB_PAGE,
  enqueueMemoryJob,
  claimMemoryJob,
  withMemoryJobLease,
  finishMemoryJob,
  memoryJobCounts,
  latestProjectMemoryJob,
  sessionMemoryWindow,
  parseJobManifest,
  enqueueBatchJob,
  claimJob,
  stageJob,
  reserveJobStorage,
  MEMORY_JOB_STORAGE_RESERVATION_BYTES,
  publishJob,
  finishJob,
  bumpRequestedRev,
  cancelJob,
  retryJob,
  listJobs,
  jobById,
  jobsStagedOrRunningFor,
} from "./memory-jobs";
export type {
  MemoryJobClaim,
  MemoryJobCounts,
  SessionMemoryActivity,
  JobStatus,
  JobProcessor,
  JobPurpose,
  BatchProcessor,
  BatchPurpose,
  JobOrigin,
  JobOutcome,
  JobInterval,
  JobManifest,
  BatchJobInput,
  JobClaim,
  JobStaged,
  JobCoverage,
  JobView,
  JobRow,
  JobFilter,
  JobRetryOutcome,
} from "./memory-jobs";
/*
  Delivery B: the typed local facts of a stream and the reservation of a paid call. The facts are
  the closed record of what a program did (never what it said); the reservation is the row that
  is written BEFORE the call so that two callers cannot both spend the last call of the day.
 */
export {
  FACT_KINDS,
  COMMAND_FAMILIES,
  EDIT_KINDS,
  TEST_OUTCOMES,
  FAILURE_KINDS,
  LIFECYCLE_EVENTS,
  FACT_PATHS_MAX,
  FACT_PATH_LENGTH_MAX,
  FACT_CONTRACT_IDS_MAX,
  FACT_SUITES_MAX,
  FACTS_QUERY_LIMIT,
  FACTS_QUERY_MAX,
  FACT_RETENTION_DAYS,
  validateFactPayload,
  recordFacts,
  deleteFactsOfSource,
  pruneFacts,
  factsForProject,
  factsInRange,
  factCounts,
  compareParserVersions,
} from "./session-facts";
export { transferProjectUsage, settleProjectUsageForDeletion, settleAgentUsageForDeletion } from "./memory-rehome";
export type {
  FactKind,
  FactPayload,
  FactPayloads,
  FactInput,
  FactRow,
  FactCounts,
  CommandFamily,
  EditKind,
  TestOutcome,
  FailureKind,
  LifecycleEvent,
} from "./session-facts";
export {
  reserveModelCall,
  markSent,
  completeReservation,
  markUncertain,
  releaseReservation,
  reservationById,
  reservationsForJob,
  paidAttemptsForJob,
  localDayOf,
  COUNTED_STATES,
  PAID_STATES,
} from "./model-reservations";
export type {
  ReservationOrigin,
  ReservationState,
  ReservationRefusal,
  ReservationCaps,
  ReservationPolicy,
  ReservationInput,
  ReservationResult,
  ReservationExpectation,
  ReservationUsage,
  ReservationRow,
} from "./model-reservations";
export * from "./handoffs";
export { MEMORY_EXPORT_VERSION, exportProjectMemory } from "./memory-export";
export type {
  ExportedDecision,
  ExportedDeletions,
  ExportedLatestOffer,
  ExportedMemoryJob,
  ExportedNote,
  ExportedOffers,
  MemoryExport,
} from "./memory-export";
/*
  The memory contract of delivery A (private/memory-build-plan.md, §22): revisions photograph a
  delivered object, contexts and offers record what was prepared for whom, sources and cursors
  hold where a permitted reader stands, dependencies and deletions make withdrawal and purge
  walkable. Each module names its own table; none of them is a second store of the domain.
 */
export {
  REVISION_KINDS,
  REVISION_AUTHORITIES,
  REVISION_REASONS,
  recordRevision,
  recordRevisions,
  readRevision,
  latestRevision,
  revisionHistory,
  revisionRefsOf,
  ensureBaselineRevisions,
  ensureDeliveryModes,
  notePayload,
  criterionPayload,
  decisionPayload,
  commitmentPayload,
  observationPayload,
  observationDisposition,
  observationAuthority,
  scopeOf,
  scopeKindFor,
  noteAuthority,
  criterionAuthority,
  decisionAuthority,
  commitmentAuthority,
} from "./memory-revisions";
export type {
  RevisionKind,
  RevisionAuthority,
  RevisionReason,
  RevisionScopeKind,
  RevisionCoverage,
  RevisionInput,
  RevisionRow,
  NoteRecord,
  CriterionRecord,
  DecisionRecord,
  CommitmentRecord,
  ObservationRecord,
} from "./memory-revisions";
/*
  Delivery D: the typed conditions and exceptions of a criterion, the origin key of an
  observation and the support families behind an inference. twin.ts holds the vocabulary and the
  validators with no catalog access; support-families.ts recomputes the evidence from the rows.
 */
export {
  SUPPORT_POLICY_VERSION,
  SUPPORT_FAMILIES_FLOOR,
  CASE_ORIGIN_KEY_MAX,
  COPIED_ORIGIN_PREFIX,
  TEACH_ORIGIN_PREFIX,
  UNKNOWN_ORIGIN,
  SUPPORT_FAMILIES_MAX,
  SUPPORT_REFS_MAX,
  SUPPORT_REVISIONS_PER_FAMILY_MAX,
  SUPPORT_FAMILY_KINDS,
  InvalidTwinInput,
  beliefPredicate,
  storedPredicate,
  validateCaseOriginKey,
  OBSERVATION_KINDS,
  UNKNOWN_REFERENT,
  REFERENT_MAX,
  validateObservationKind,
  validateReferent,
  isAmbiguousReaction,
  originCounts,
  originKind,
  validateSupportEvidence,
  beliefSupportEvidence,
  storedSupportEvidence,
  lastTopicSynthesis,
} from "./twin";
export type { SupportFamilyKind, SupportFamily, SupportCounts, SupportEvidence, BeliefWrite, ObservationKind } from "./twin";
export { familiesOf, supportCountsOf, supportEvidenceOf, supportOf, publishableByPolicy } from "./support-families";
export type { SupportObservation } from "./support-families";
/*
  Delivery C: the checks a note, criterion, decision or commitment carries and what observing
  them wrote down; the commitments themselves. The vocabulary of a check (purposes, kinds) is
  exported once, from memory-checks.ts; commitments.ts reads it from there.
 */
export {
  CHECK_PURPOSES,
  CHECK_KINDS,
  CHECK_ECOSYSTEMS,
  CHECK_DOMAINS,
  CHECK_TARGET_MAX,
  CHECK_LITERAL_MAX,
  CHECK_PATH_SEGMENTS_MAX,
  CHECK_NAME_MAX,
  COMPLETION_CHECKS_MAX,
  InvalidCheck,
  validateCheck,
  checksOf,
  putCheck,
  removeCheck,
  checkCount,
} from "./memory-checks";
export type {
  CheckPurpose,
  CheckKind,
  CheckEcosystem,
  CheckDomain,
  ManifestScriptExpected,
  DirectDependencyExpected,
  StructuredKeyExpected,
  CheckShape,
  CheckExpected,
  CheckHeader,
  Check,
  CheckInput,
  PutCheckResult,
  CheckCounts,
} from "./memory-checks";
export {
  OUTCOME_KINDS,
  OUTCOME_RESULTS,
  INSPECTED_STATES,
  DELIVERED_BEFORE,
  OWNER_VERDICTS,
  FRESHNESS_MS,
  OUTCOMES_PAGE,
  OUTCOMES_PAGE_MAX,
  INSPECTED_MAX,
  SOURCE_REFS_MAX,
  validateEnvironment,
  validateEvidence,
  occurrenceIdOf,
  recordObservation,
  openIncident,
  judgeIncident,
  outcomesFor,
  outcomeById,
  latestObservation,
  latestOutcomeEnvironment,
  staleOf,
  deliveredBefore,
  outcomeCounts,
} from "./memory-outcomes";
export type {
  OutcomeKind,
  OutcomeResult,
  InspectedState,
  DeliveredBefore,
  OwnerVerdict,
  InspectedFile,
  Environment,
  Evidence,
  ObservationInput,
  IncidentInput,
  OutcomeRow,
  // The Twin's `ObservationRow` (queries.ts) keeps that name; a check's observation is an OutcomeRow.
  ObservationRow as CheckObservationRow,
  OccurrenceView,
  OutcomeFilter,
  OutcomeCounts,
} from "./memory-outcomes";
export {
  COMMITMENT_TEXT_MAX,
  CHECKS_MAX,
  COMMITMENT_PAGE,
  COMMITMENT_PAGE_MAX,
  OBSERVATIONS_PER_COMMITMENT,
  COMMITMENT_STATUSES,
  PREDICATE_LEAF_KINDS,
  PREDICATE_SHAPE_LIMITS,
  validatePredicateShape,
  checkOf,
  createCommitment,
  reviseCommitment,
  fulfilCommitment,
  cancelCommitment,
  linkCommitments,
  listCommitments,
  commitmentCounts,
  commitmentsByTask,
  lookCountsOf,
  commitmentById,
} from "./commitments";
export type {
  LookCount,
  CommitmentStatus,
  PredicateLeafKind,
  PredicateLeaf,
  PredicateNode,
  Predicate,
  Resolution,
  ResolutionInput,
  CommitmentObservation,
  CommitmentView,
  CommitmentConflict,
} from "./commitments";
export { resolveContext, touchContext, contextById, contextsForProject } from "./memory-contexts";
export type { ContextRow, ResolveContextInput, ResolvedContext, ContextLifecycleKind } from "./memory-contexts";
export {
  recordOffer,
  recordAttempt,
  recordReception,
  offerById,
  offersForContext,
  offersForProject,
  offersByContractIds,
  offerByRequestKey,
  deliverySummary,
  OfferConflict,
} from "./memory-offers";
export type { OfferInput, OfferRow, OfferEvent, ReceptionInput, DeliverySummary, AttemptResult } from "./memory-offers";
export {
  upsertSource,
  recordSourceFingerprint,
  replaceSourceGeneration,
  sourceById,
  sourcesByStream,
  listSources,
  allSources,
  purgeSourceIdentity,
  ensureCursor,
  claimCursor,
  advanceCursor,
  blockCursor,
  unblockCursor,
  resolveCursorGap,
  sourceGaps,
  SOURCE_GAPS_MAX,
  revokeCursors,
  cursorsFor,
  allCursorsFor,
  cursorCounts,
  cursorLeased,
} from "./memory-sources";
export type {
  SourceRow,
  CursorRow,
  ResolvedGap,
  SourceInput,
  CursorKey,
  CursorInit,
  CursorExpectation,
  CursorPatch,
  CursorGap,
  CursorFilter,
  SourceOrigin,
  SourceStatus,
  SourceEntrypoint,
  CursorPurpose,
  CursorState,
} from "./memory-sources";
export {
  DEPENDENCY_WALK_DEPTH,
  addDependencies,
  dependencyKeyOf,
  dependentsOfRevisions,
  dependentsOfSources,
  dependenciesOf,
  deleteDependenciesOfServings,
  edgesByInputs,
  edgesOfDependents,
} from "./memory-dependencies";
export type {
  DependencyEdge,
  DependencyGroup,
  DependencyRow,
  DependencyRelation,
  DependencyGroupMode,
  DependentEnd,
  InputEnd,
  DependentIds,
} from "./memory-dependencies";
export {
  DELETION_JOURNAL_FILE,
  DELETION_JOURNAL_SCHEMA_VERSION,
  DELETION_BATCH,
  deletionJournalPath,
  ensureDeletionJournal,
  beginDeletion,
  planDeletion,
  runDeletionBatches,
  deletionById,
  checkpointDeletionFiles,
  FILE_CLEANUP_ATTEMPTS_MAX,
  listDeletions,
  deletionGeneration,
  withdrawnRevisionIds,
  memoryReadBarrier,
  obsoleteJobs,
  liveJobsFor,
  blockedSourceIds,
} from "./memory-purge";
export type {
  JobObsoleteReason,
  PurgeItemKind,
  PurgeTarget,
  DeletionOperation,
  DeletionIntent,
  DeletionRow,
  DeletionState,
  DeletionStore,
  QuarantineReason,
  JournalState,
  DeletionBegun,
  DeletionCounts,
  DeletionPlan,
  DeletionReceipt,
  DeletionProgress,
} from "./memory-purge";
export {
  QuotaExceeded,
  isQuotaExceeded,
  usageBytesOf,
  offerUsageBytes,
  checkedLimits,
  usageProjectsOf,
  usageProjectOf,
  chargeUsage,
  chargeUsages,
  creditUsage,
  creditUsages,
  usageOf,
  quotaState,
  reconcileUsage,
} from "./memory-usage";
export type {
  UsageScopeKind,
  UsageOrigin,
  UsageLimits,
  UsageOptions,
  UsageCharge,
  UsageTotals,
  QuotaScopeState,
  QuotaState,
  UsageReconciliation,
} from "./memory-usage";
export {
  createRun,
  finishRun,
  setRunStatus,
  reapStaleRuns,
  findRunningRun,
  getRun,
  getRunWithProject,
  listProjectRuns,
  listAllRuns,
  findUpgradeTarget,
  findKnownFailure,
  listSecurityTargets,
} from "./runs";
export type { RunStatus, SecurityTarget } from "./runs";
export * as schema from "./schema";
