/**
 * Main entry point: schema, queries, and types. Deliberately **without driver**.
 *
 * `openDatabase` lives in `@panoma/db/client` because it drags PGlite, which is a WASM module. Any
 * packer that sees it tries to put it in the bundle and breaks it (it replaces the global `URL`
 * and `fs.readFile` stops recognizing its own). By separating it, the web can import queries and
 * types normally and load the driver only at runtime.
 */
export type { Database } from "./client";
export { ingestPortfolio, idFor, pruneSnapshots, SNAPSHOTS_PER_PROJECT } from "./ingest";
export type { IngestResult, IngestPayload, SerializedFamily } from "./ingest";
export { queueWrite } from "./queue";
export {
  listProjects,
  getProject,
  getProjectIcon,
  getProjectLocation,
  listFamilies,
  listPackages,
  listUnsavedWork,
  listDiskUsage,
  getDiskTotals,
  listProjectRoots,
  getDailyReport,
  saveDiskUsage,
  saveAiSummary,
  saveMdReview,
  saveProjectAccounts,
  saveBuildCheck,
  setHidden,
  excludeProject,
  forgetProjectsUnder,
  unexcludeProject,
  listHidden,
  getStats,
  stateOf,
  DORMANT_DAYS,
  IDLE_DAYS,
  saveNorth,
  getNorth,
  tasteScore,
  briefScore,
  saveModelCall,
  modelSpendToday,
  saveReview,
  getReview,
  neverReviewed,
  saveLook,
  listLooks,
  getLook,
  projectByIdentity,
  lookedAt,
  autoLooksToday,
  modelSpendByKind,
  beliefChurn,
  saveSynthesisPass,
  startOfMonthsAgo,
  monthOf,
  startOfDay,
  citedVerdictIds,
  corpusProgress,
  tasteReach,
  markVerdictsDistilled,
  readVerdictIds,
  remapObservations,
  saveVerdicts,
  listVerdicts,
  deleteVerdicts,
  projectNamesByIdentity,
  saveObservations,
  listObservations,
  observationTopics,
  setObservationTopics,
  insertBeliefs,
  updateBelief,
  listBeliefs,
  signBelief,
  vetoBelief,
  retireBeliefs,
  setBeliefScope,
  setBeliefTopics,
  markPublished,
  resolveProposal,
  standsUp,
  ALIVE,
  SUPPORT_FLOOR,
  inTransaction,
  saveDesignFingerprint,
  getDesignFingerprint,
  portfolioDesign,
  familia,
  esquina,
} from "./queries";
export type {
  ProjectAccount,
  BuildCheckVerdict,
  ProjectCard,
  ProjectState,
  FamilyView,
  PortfolioStats,
  PackageRow,
  UnsavedProject,
  DiskRow,
  DiskTotals,
  HiddenView,
  DailyReport,
  DailyProject,
  DailyCritic,
  DailyProposal,
  DailyCommit,
  DirectorProject,
  TasteScore,
  BriefScore,
  TasteReach,
  PortfolioDesign,
  DesignShare,
  NewVerdict,
  Verdict,
  TasteCitation,
  NewObservation,
  ObservationRow,
  TopicCount,
  BeliefState,
  BeliefCitation,
  BeliefSupport,
  NewBelief,
  BeliefRow,
  PublishedLine,
  NewModelCall,
  ModelSpend,
  KindSpend,
  ChurnMonth,
  SynthesisPass,
  VerdictsSaved,
  CorpusProgress,
  StoredCritique,
  ReviewRow,
  StoredFinding,
  LookFired,
  NewLook,
  LookRow,
} from "./queries";
export {
  createAgent,
  deleteAgent,
  rotateAgentKey,
  authenticateAgent,
  resolveProject,
  getAgentContext,
  openSession,
  closeSession,
  logActivity,
  LOG_SUMMARY_MAX,
  LOG_DETAILS_MAX,
  createTask,
  getTask,
  assignedFindings,
  assignedCritiques,
  discardedCritiques,
  discardedFindings,
  discardTask,
  listProjectLaunches,
  recordLaunch,
  launchedTasks,
  claimTask,
  completeTask,
  listProjectActivity,
  listSessionActivities,
  searchJournal,
  listProjectTasks,
  listAllActivity,
  listAgents,
  newId,
} from "./agents";
export type { AgentContext, CreatedAgent, JournalHit, NewLaunch } from "./agents";
export {
  NOTE_BUDGET,
  NOTE_MAX,
  NOTE_PENDING_MAX,
  NOTE_SLEEPING_MAX,
  addHumanNote,
  decideNote,
  listProjectNotes,
  noteUsage,
  proposeNote,
  challengeNote,
  listSentinels,
  notesAt,
  recordServing,
  scaleReport,
  setSentinels,
  bridgeCounts,
  triggerMatches,
  validTrigger,
} from "./notes";
export type { Challenge, NoteRefusal, ProjectNote, ScaleReport, Sentinel } from "./notes";
export {
  CONSULT_MAX,
  CONSULT_PENDING_MAX,
  doubleReport,
  draftConsultation,
  labelConsultation,
  listProjectConsultations,
  recordConsultation,
  staleDrafting,
} from "./consultations";
export type { Consultation, DoubleReport } from "./consultations";
export {
  createRun,
  finishRun,
  setRunStatus,
  reapStaleRuns,
  findRunningRun,
  getRun,
  getRunWithProject,
  listProjectRuns,
  listAllRuns,
  findUpgradeTarget,
  findKnownFailure,
  listSecurityTargets,
} from "./runs";
export type { RunStatus, SecurityTarget } from "./runs";
export * as schema from "./schema";
