import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  analyzeProject,
  CLAUDE_BRIDGE,
  composeBlockData,
  pickAgentDoc,
  renderPanomaBlock,
  TASTE_GLOBAL_ONLY,
  readTaste,
  shotsOpen,
  tasteDigest,
  TASTE_CAP,
  upsertPanomaBlock,
  type CatalogMdContext,
  type ProjectAnalysis,
} from "@panoma/core";
import { getProject, listProjectTasks, resolveProject, type Database } from "@panoma/db";
import { OPEN_STATUSES } from "./tasks";

/*
  The context block within the agents' instruction file.
  From the local analysis come the runbook and the stack —the truth of the disk, right now— and
  from the catalog what only the catalog knows: outdated dependencies, security warnings, open
  tasks, which agents have been here. If the project is not in the catalog, the block keeps the
  local part: less complete, never invented.
  Who writes, and where, is a security decision and not one of convenience: CLI writes on the
  user's terminal with the user's permissions, and the watcher only on roots that are already in
  the catalog and carry the markers — having put them there is the opt-in. HTTP writes only one
  path, `/api/md/apply`, and with the step closed to what made the idea dangerous: the root comes
  out of the catalog by slug (never from the client), the content is generated by Panoma from
  structured data, the user's click is consent, and network exposure requires a credential. What
  does not exist is a path that writes someone else's text or in someone else's paths — that would
  be an instruction injection channel to all the agents of this machine.
 */

/** What the catalog contributes to the block of a project. `undefined` if it is not filed. */
export async function catalogMdContext(
  database: Database,
  root: string,
): Promise<CatalogMdContext | undefined> {
  const row = await resolveProject(database, { cwd: root });
  /*
    Only with exact root match. `resolveProject` falls to the deepest ancestor, which is correct
    for an agent working in a subfolder — and incorrect here: the block of `packages/x` with the
    name, notices, and tasks of the parent monorepo would be mixing two projects without saying
    so. Without exact match, the project «is not logged» and the block remains with the truth from
    the disk.
   */
  if (!row || row.root !== root) return undefined;

  const context: CatalogMdContext = { name: row.name };
  /*
    By `enrichedAt` and not by nulls: `outdatedDeps` and company are born with `default(0)`, so in
    a never enriched project those zeros are not facts, they are the factory value. “0 overdue” as
    a statement only exists after an enrichment.
   */
  if (row.enrichedAt !== null) {
    context.outdated = row.outdatedDeps;
    context.vulns = row.vulnCount;
    if (row.vulnCritical > 0) context.critical = row.vulnCritical;
  }

  const [detail, tasks] = await Promise.all([
    getProject(database, row.slug),
    listProjectTasks(database, row.id),
  ]);
  if (detail) {
    context.advisories = detail.advisories.map((a) => ({
      package: a.packageName ?? "",
      id: a.advisoryId,
    }));
    context.agents = detail.agents.map((a) => ({ name: a.agentName, commits: a.commits ?? 0 }));
  }
  const open = tasks.filter((task) => OPEN_STATUSES.includes(task.status)).length;
  if (open > 0) context.openTasks = open;

  /*
    Only the conclusive verdicts travel to the block: 'ok' and 'failed' are events that can change
    an agent's afternoon; 'no build script' would be disguised noise.
   */
  const check = detail?.decision?.buildCheck as
    | { status?: string; at?: string; command?: string }
    | null
    | undefined;
  if (check && (check.status === "ok" || check.status === "failed") && check.at) {
    context.build = { status: check.status, at: check.at };
    if (check.command) context.build.command = check.command;
  }

  return context;
}

export interface MdSyncResult {
  file: string;
  created: boolean;
  changed: boolean;
  /** If the CLAUDE.md of the bridge was also released — see option `bridge`. */
  bridged: boolean;
}

/**
 * Regenerate (or create, with `create` ) the Panoma block in the instruction file.
 *
 * End-to-end deterministic: if reality hasn't changed, the bytes don't change and nothing is
 * written — which is what allows it to be called from the watcher without dirtying diffs or waking
 * itself in a loop.
 */
export async function syncProjectDoc(
  root: string,
  options: { create?: boolean; bridge?: boolean; analysis?: ProjectAnalysis; database: Database },
): Promise<MdSyncResult | { error: "no-block" } | { error: "broken"; detail: string }> {
  const picked = await pickAgentDoc(root);
  if (!picked.managed && !options.create) return { error: "no-block" };

  const analysis = options.analysis ?? (await analyzeProject(root));
  const catalog = await catalogMdContext(options.database, root);
  /*
    The portrait of taste goes down here, to the only channel that all agents read without
    configuring anything. Empty when there is nothing approved, which is what makes emptying
    TASTE.md the way to not publish it.
   */
  /*
    The portrait, trimmed to this project: the general plus what was restricted here. It is what
    makes the limit stop pressing — an agent does not pay tokens for the pleasure of the other one
    hundred and eleven projects — and also what prevents a true sentence in one place from
    descending as instruction to the next one.
    The name and not the identity, because it is what the file writes and what a person can
    correct by opening it. Without a catalog there is no name, and only the general is removed,
    which is correct: without knowing what project this is, the limited cannot be claimed.
   */
  /*
    And with `TASTE_GLOBAL_ONLY` when the project is not checked in, not with `undefined`: without
    a name nothing is filtered, so a single folder would receive the entire portrait with the
    annotations of all the other projects inside. 'I don't know which project this is' and 'show
    everything' are different things, and here they were the same.
   */
  const taste = tasteDigest(await readTaste(), TASTE_CAP, catalog?.name ?? TASTE_GLOBAL_ONLY);
  /*
    The mailbox is looked at, not created: assembling it is a matter of `panoma md init`, which is
    an explicit gesture of the person. This is also executed from the watcher, in every commit of
    every monitored project, and a folder that appears on its own in someone's repository because
    they made a commit is exactly what cannot happen.
   */
  const shots = await shotsOpen(root);
  const block = renderPanomaBlock(composeBlockData(analysis, catalog, { taste, shots }));

  let next: string;
  try {
    next = upsertPanomaBlock(picked.content, block);
  } catch (reason) {
    return { error: "broken", detail: reason instanceof Error ? reason.message : String(reason) };
  }

  const changed = next !== (picked.content ?? "");
  if (changed) await writeFile(join(root, picked.file), next, "utf8");

  /*
    The bridge for Claude Code, only with `bridge` — which is the way of saying "this was
    requested with a click": the button's path always passes it, the watcher never does. Claude
    Code doesn't read AGENTS.md (its documentation says so literally), so without a CLAUDE.md
    importing it with the at-sign, the block above is invisible to the tool. Running that file in
    every monitored commit is exactly what the opt-in exists to prevent; and an existing one is
    user prose and is not to be touched, even if it's a link that doesn't matter — for that case,
    there is the notice in the file.
   */
  let bridged = false;
  if (options.bridge && picked.file === "AGENTS.md") {
    const claude = await readFile(join(root, "CLAUDE.md"), "utf8").catch(() => undefined);
    if (claude === undefined) {
      await writeFile(join(root, "CLAUDE.md"), CLAUDE_BRIDGE, "utf8");
      bridged = true;
    }
  }

  return { file: picked.file, created: picked.content === undefined, changed, bridged };
}

/**
 * The look-out variant: it only acts if the user has already placed the block, and it never
 * launches — an instruction file cannot knock down the re-analysis that brought it here.
 */
export async function syncManagedDoc(
  root: string,
  database: Database,
  analysis?: ProjectAnalysis,
): Promise<void> {
  try {
    const result = await syncProjectDoc(root, { create: false, analysis, database });
    if ("error" in result && result.error === "broken") {
      console.warn(`[vigía] el bloque de panoma en ${root} está roto: ${result.detail}`);
    }
  } catch (reason) {
    console.warn(`[vigía] no se pudo regenerar el bloque de ${root}:`, reason);
  }
}
