-- Delivery B of the memory plan: typed session facts, jobs with an id of their own, and the
-- model-call reservation. Generated by drizzle-kit and rewritten by hand where the generator
-- cannot know the data: the primary key of `memory_jobs` moves from `session_id` to `id`, and
-- every legacy row is backfilled deterministically (`legacy:<session_id>`, keyed by the session,
-- scoped to the session's project, the baseline manifest and its canonical hash) before the new
-- columns are made NOT NULL. The two checks that already existed since 0053 are dropped and
-- re-created with the widened list; everything else is additive.
CREATE TABLE "session_facts" (
	"id" text PRIMARY KEY NOT NULL,
	"source_id" text NOT NULL,
	"byte_offset" bigint NOT NULL,
	"sub_index" integer NOT NULL,
	"parser_version" text NOT NULL,
	"ingest_seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "session_facts_ingest_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" text,
	"identity" text,
	"recipient_key" text,
	"kind" text NOT NULL,
	"payload" jsonb NOT NULL,
	"observed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "session_facts_offset_check" CHECK ("session_facts"."byte_offset" >= 0 and "session_facts"."sub_index" >= 0),
	CONSTRAINT "session_facts_kind_check" CHECK ("session_facts"."kind" in ('read', 'edit', 'command', 'test_result', 'failure', 'commit', 'lifecycle', 'receipt_seen'))
);
--> statement-breakpoint
ALTER TABLE "memory_dependencies" DROP CONSTRAINT "memory_dependencies_dependent_check";--> statement-breakpoint
ALTER TABLE "memory_jobs" DROP CONSTRAINT "memory_jobs_pkey";--> statement-breakpoint
ALTER TABLE "memory_jobs" ALTER COLUMN "session_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_dependencies" ADD COLUMN "dependent_job_id" text;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "id" text;--> statement-breakpoint
UPDATE "memory_jobs" SET "id" = 'legacy:' || "session_id";--> statement-breakpoint
ALTER TABLE "memory_jobs" ALTER COLUMN "id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD CONSTRAINT "memory_jobs_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "lease_until" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "processor" text DEFAULT 'legacy_session' NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "work_key" text;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "scope_key" text;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "project_id" text;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "purpose" text DEFAULT 'legacy_memory' NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "origin" text DEFAULT 'legacy' NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "input_manifest" jsonb DEFAULT '{"schemaVersion":1,"processor":"legacy_session","coverage":"baseline_only"}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "input_hash" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "requested_rev" bigint DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "rev" bigint DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD COLUMN "staged_output" jsonb;--> statement-breakpoint
UPDATE "memory_jobs" SET "work_key" = "memory_jobs"."session_id", "scope_key" = "s"."project_id", "project_id" = "s"."project_id"
  FROM "agent_sessions" AS "s" WHERE "s"."id" = "memory_jobs"."session_id";--> statement-breakpoint
UPDATE "memory_jobs" SET "work_key" = "id", "scope_key" = 'unknown' WHERE "work_key" IS NULL;--> statement-breakpoint
UPDATE "memory_jobs" SET "input_hash" = 'fb19453d5f6386ea1686e18a7fbfd2504b9d964737a71df6071d6bfafbf3b9fd' WHERE "input_hash" = '';--> statement-breakpoint
ALTER TABLE "memory_jobs" ALTER COLUMN "work_key" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "memory_jobs" ALTER COLUMN "scope_key" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "origin" text DEFAULT 'legacy' NOT NULL;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "state" text DEFAULT 'completed' NOT NULL;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "attempt_key" text;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "job_id" text;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "budget_day" date;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "reserved_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "sent_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "finished_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "model_calls" ADD COLUMN "reservation_rev" bigint DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "session_facts" ADD CONSTRAINT "session_facts_source_id_memory_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."memory_sources"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_facts" ADD CONSTRAINT "session_facts_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "session_facts_identity_idx" ON "session_facts" USING btree ("source_id","byte_offset","sub_index","parser_version");--> statement-breakpoint
CREATE UNIQUE INDEX "session_facts_ingest_idx" ON "session_facts" USING btree ("ingest_seq");--> statement-breakpoint
CREATE INDEX "session_facts_project_idx" ON "session_facts" USING btree ("project_id","ingest_seq");--> statement-breakpoint
CREATE INDEX "session_facts_source_idx" ON "session_facts" USING btree ("source_id","byte_offset");--> statement-breakpoint
ALTER TABLE "memory_dependencies" ADD CONSTRAINT "memory_dependencies_dependent_job_id_memory_jobs_id_fk" FOREIGN KEY ("dependent_job_id") REFERENCES "public"."memory_jobs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD CONSTRAINT "memory_jobs_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "model_calls" ADD CONSTRAINT "model_calls_job_id_memory_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."memory_jobs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "memory_dependencies_dependent_job_idx" ON "memory_dependencies" USING btree ("dependent_job_id");--> statement-breakpoint
CREATE INDEX "memory_jobs_project_idx" ON "memory_jobs" USING btree ("project_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "memory_jobs_work_idx" ON "memory_jobs" USING btree ("processor","work_key");--> statement-breakpoint
CREATE UNIQUE INDEX "memory_jobs_legacy_session_idx" ON "memory_jobs" USING btree ("session_id") WHERE processor = 'legacy_session';--> statement-breakpoint
CREATE INDEX "model_calls_budget_idx" ON "model_calls" USING btree ("kind","budget_day","origin","state");--> statement-breakpoint
CREATE UNIQUE INDEX "model_calls_attempt_idx" ON "model_calls" USING btree ("attempt_key") WHERE attempt_key is not null;--> statement-breakpoint
ALTER TABLE "memory_dependencies" ADD CONSTRAINT "memory_dependencies_dependent_check" CHECK (("memory_dependencies"."dependent_revision_id" is not null)::int + ("memory_dependencies"."dependent_serving_id" is not null)::int + ("memory_dependencies"."dependent_job_id" is not null)::int = 1);--> statement-breakpoint
ALTER TABLE "memory_jobs" DROP CONSTRAINT IF EXISTS "memory_jobs_status_check";--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD CONSTRAINT "memory_jobs_status_check" CHECK ("memory_jobs"."status" in ('pending', 'running', 'staged', 'deferred', 'failed', 'complete', 'cancelled', 'obsolete'));--> statement-breakpoint
ALTER TABLE "memory_jobs" DROP CONSTRAINT IF EXISTS "memory_jobs_attempts_check";--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD CONSTRAINT "memory_jobs_attempts_check" CHECK ("memory_jobs"."attempts" >= 0);--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD CONSTRAINT "memory_jobs_origin_check" CHECK ("memory_jobs"."origin" in ('legacy', 'manual', 'automatic'));--> statement-breakpoint
ALTER TABLE "memory_jobs" ADD CONSTRAINT "memory_jobs_rev_check" CHECK ("memory_jobs"."rev" > 0 and "memory_jobs"."requested_rev" > 0);--> statement-breakpoint
ALTER TABLE "model_calls" ADD CONSTRAINT "model_calls_origin_check" CHECK ("model_calls"."origin" in ('legacy', 'manual', 'automatic'));--> statement-breakpoint
ALTER TABLE "model_calls" ADD CONSTRAINT "model_calls_state_check" CHECK ("model_calls"."state" in ('reserved', 'sent', 'completed', 'uncertain', 'released'));--> statement-breakpoint
ALTER TABLE "model_calls" ADD CONSTRAINT "model_calls_reservation_rev_check" CHECK ("model_calls"."reservation_rev" > 0);
