-- Delivery D of the memory plan: the typed conditions, exceptions and support evidence of a
-- criterion, the delivery revision and case origin of an observation, and the job and topic
-- fingerprint of a synthesis pass. Generated by drizzle-kit, additive throughout. The backfill of
-- `observations.memory_rev` is the column default: the plan says the highest photographed
-- revision or 1, and no observation was ever photographed before this migration (the
-- `observation` revision kind existed since delivery A, nothing wrote it), so every legacy row
-- starts at 1 and `ensureBaselineRevisions` photographs it there. Null `case_origin_key` and
-- null `support_evidence` mean a legacy row whose origin is unknown, never a checked absence.
ALTER TABLE "beliefs" ADD COLUMN "conditions" jsonb;--> statement-breakpoint
ALTER TABLE "beliefs" ADD COLUMN "exceptions" jsonb;--> statement-breakpoint
ALTER TABLE "beliefs" ADD COLUMN "support_evidence" jsonb;--> statement-breakpoint
ALTER TABLE "observations" ADD COLUMN "memory_rev" bigint DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "observations" ADD COLUMN "case_origin_key" text;--> statement-breakpoint
ALTER TABLE "synthesis_passes" ADD COLUMN "job_id" text;--> statement-breakpoint
ALTER TABLE "synthesis_passes" ADD COLUMN "input_hash" text;--> statement-breakpoint
ALTER TABLE "synthesis_passes" ADD CONSTRAINT "synthesis_passes_job_id_memory_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."memory_jobs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "observations_origin_idx" ON "observations" USING btree ("case_origin_key");--> statement-breakpoint
CREATE INDEX "synthesis_passes_topic_hash_idx" ON "synthesis_passes" USING btree ("topic","input_hash");--> statement-breakpoint
ALTER TABLE "observations" ADD CONSTRAINT "observations_memory_rev_check" CHECK ("observations"."memory_rev" > 0);