-- Delivery D of the memory plan, second part: what the distiller read a turn as (`kind`) and what
-- it was about (`referent`). Generated by drizzle-kit, additive: both columns stay null on every
-- legacy row, which means "not recorded" and never "checked". The ambiguous reaction the plan
-- names («perfecto» with no object, §21.3) is a row of kind `reaction` with the literal referent
-- `unknown`; it keeps its topic, its quote and its origin, and no synthesis reads it as a
-- preference.
ALTER TABLE "observations" ADD COLUMN "kind" text;--> statement-breakpoint
ALTER TABLE "observations" ADD COLUMN "referent" text;--> statement-breakpoint
ALTER TABLE "observations" ADD CONSTRAINT "observations_kind_check" CHECK ("observations"."kind" is null or "observations"."kind" in ('reaction', 'choice', 'reason', 'condition', 'exception', 'counterexample', 'correction'));