-- The storage accounting of plan §25.3: the logical bytes of derived memory content per catalog
-- and per project, kept by the writers and compared with the owner's quota. Generated by
-- drizzle-kit, additive. The rows are born empty; `reconcileUsage` fills them from the payloads
-- already in the catalog on the first heartbeat, so a catalog that migrates with legacy content
-- reports its size and is never pruned to fit.
CREATE TABLE "memory_usage" (
	"scope_kind" text NOT NULL,
	"scope_key" text NOT NULL,
	"bytes" bigint DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "memory_usage_scope_kind_scope_key_pk" PRIMARY KEY("scope_kind","scope_key"),
	CONSTRAINT "memory_usage_scope_kind_check" CHECK ("memory_usage"."scope_kind" in ('catalog', 'project')),
	CONSTRAINT "memory_usage_bytes_check" CHECK ("memory_usage"."bytes" >= 0)
);
