import { analyzeProject, classifyOrigin, deduceIdentity } from "@panoma/core";
import { getProject, ingestPortfolio, queueWrite } from "@panoma/db";
import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { sameOrigin } from "@/lib/guard";
import { syncProjectDoc } from "@/lib/md-sync";
import { localeFrom, t } from "@/lib/i18n";

/**
 * The button in the .md section: creates or regenerates the context block, really.
 *
 * It is the only HTTP path that writes a user's file, and the exception is measured. The original
 * rule —'no path writes files'— blocked anyone from the network from writing instructions wherever
 * they wanted. Here that path does not exist: the root comes out of the CATALOG by slug (never
 * from the client), the content is generated by Panoma from structured data (the same
 * deterministic block as always, plus the `CLAUDE_BRIDGE` bridge when missing — another constant
 * from Panoma, not a single letter from the client), the user's click is the consent, and network
 * exposure requires a credential from the moment `panoma up --network` requests it. What still
 * does not exist is a route that writes someone else's text or in someone else's routes — see
 * `lib/md-sync.ts`.
 *
 * After writing, re-analyze and ingest: the record that reloads has to show the newly created
 * file, not the photo from before the click.
 *
 * **Without `localOperatorOnly`, and decided, not forgotten.** The routes that execute code or
 * touch the user's git require being on the computer itself. This one executes nothing: it writes
 * a text that generates Panoma in a file chosen by the catalog, and the result can be seen in a
 * `git diff` and undone with a `git checkout`. It is bounded and reversible writing, not hands on
 * the keyboard; closing it off from the network would remove the fix from the couch without
 * removing any risk not already covered by the credential. See `lib/guard.ts` and
 * `api/gates.test.ts`.
 */
export async function POST(request: Request) {
  const blocked = sameOrigin(request);
  if (blocked) return blocked;

  const locale = localeFrom(request);

  if (process.env["DATABASE_URL"]) {
    return Response.json(
      { error: t(locale, "api.localOnly", { action: t(locale, "api.action.writeBlock") }) },
      { status: 400 },
    );
  }

  const body = (await request.json().catch(() => ({}))) as { slug?: string; action?: string };
  if (!body.slug || (body.action !== "init" && body.action !== "sync")) {
    return Response.json({ error: t(locale, "md.missingSlugAction") }, { status: 400 });
  }

  const { db: database } = await db();
  const data = await getProject(database, body.slug);
  if (!data) return Response.json({ error: t(locale, "api.noProject") }, { status: 404 });
  const root = data.project.root;

  /*
    `bridge: true` in both actions, not just in init: here the line that separates writing from
    not writing is the click, and sync is also a click. The one who never passes it is the watcher
    — see `syncManagedDoc`.
   */
  const result = await syncProjectDoc(root, {
    create: body.action === "init",
    bridge: true,
    database,
  });
  if ("error" in result) {
    if (result.error === "no-block") {
      return Response.json(
        { error: t(locale, "md.noBlock") },
        { status: 409 },
      );
    }
    return Response.json({ error: result.detail }, { status: 409 });
  }

  /*
    The re-analysis goes after writing on purpose: it is the one that sees the new file. The
    watcher would pass again in a few seconds, but the card reloads NOW.
   */
  try {
    const analysis = await analyzeProject(root);
    const identity = deduceIdentity([analysis]);
    const origin = classifyOrigin(analysis, identity);
    await queueWrite(() =>
      ingestPortfolio(database, [analysis], [], undefined, [{ root, ...origin }]),
    );
  } catch {
    // The writing is already done and the watcher will re-analyze alone: one does not fail because
    // of this.
  }

  revalidatePath("/", "layout");
  return Response.json({ ok: true, ...result });
}
