import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

/**
 * A third-party notice that admits not knowing what it distributes is not a notice.
 *
 * `THIRD-PARTY-NOTICES.md` is generated by `scripts/pack-app.mjs` and is committed, so here you
 * can read what is actually published on npm. It had 21 of its 29 entries as 'undeclared' —not
 * because they didn’t declare anything: the 21 have their `license` field— but because the
 * generator read the license from `app/node_modules/.pnpm`, a folder that it itself deletes two
 * hundred lines earlier. It didn’t break anything when running, and that’s why it lasted until the
 * eve of publication.
 *
 * Both halves are checked: the file that is published, and that the generator continues aborting
 * instead of writing an excuse.
 */
describe("los avisos de licencia de lo que viaja en el paquete", () => {
  const avisos = readFileSync(new URL("../THIRD-PARTY-NOTICES.md", import.meta.url), "utf8");
  const generador = readFileSync(new URL("../scripts/pack-app.mjs", import.meta.url), "utf8");

  /** The summary lines: `- nombre@version — Licencia`. */
  const resumen = avisos
    .split("\n")
    .map((linea) => /^- (\S+) — (.+)$/.exec(linea))
    .filter((encontrado) => encontrado !== null)
    .map((encontrado) => ({ paquete: encontrado[1]!, licencia: encontrado[2]!.trim() }));

  it("el resumen no está vacío", () => {
    expect(resumen.length).toBeGreaterThan(20);
  });

  it("ningún paquete viaja sin licencia declarada", () => {
    const mudos = resumen.filter(({ licencia }) =>
      /sin declarar|desconocida|unknown/i.test(licencia),
    );
    expect(mudos.map(({ paquete }) => paquete)).toEqual([]);
  });

  /*
    Strong copyleft: naming it is not enough.
    `@img/sharp-libvips-darwin-arm64` is LGPL-3.0-or-later and travels as a compiled binary. It is
    pruned before entering and `check-package.mjs` refuses to package if it appears — but the
    summary still listed it for weeks, because pruning deleted the `@img` folder and in the
    registry the keys are `@img/colour`, `@img/sharp-darwin-arm64` … The notice said that we were
    redistributing LGPL when it was not true, which is the same kind of falsehood as staying
    silent when it was.
   */
  it("no se anuncia copyleft, que exigiría mucho más que un nombre", () => {
    const fuertes = resumen.filter(({ licencia }) =>
      /^(A?GPL|LGPL|MPL|EPL|CDDL|CECILL|OSL|EUPL)/i.test(licencia),
    );
    expect(fuertes.map(({ paquete, licencia }) => `${paquete} — ${licencia}`)).toEqual([]);
  });

  it("cada entrada del resumen nombra una licencia de verdad", () => {
    const raras = resumen.filter(({ licencia }) => !/^[A-Za-z0-9]/.test(licencia));
    expect(raras.map(({ paquete }) => paquete)).toEqual([]);
  });

  it("el generador aborta si no la encuentra, en vez de inventarse una", () => {
    expect(generador).not.toContain('"sin declarar"');
    expect(generador).toContain("No sé bajo qué licencia viaja esto");
  });

  /*
    The invisible residue that the tree left after each packaging.
    Some third-party license brings Windows line endings. Those CRs were reaching the generated
    file, the repository keeps everything in LF (`.gitattributes`), and then the newly written one
    differed from the committed one **only in bytes that are not visible**: `git status` always
    marked it as modified, `pack-app` saved `arbolLimpio: false`, and `prepack` refused. The
    guardian that prevents publishing without committing ended up requiring `PANOMA_PACK_SUCIO=1`
    in all releases, which is like not having it.
    Both halves are checked, like the rest of this file: that what has been committed is clean,
    and that the generator continues normalizing at the gate.
   */
  it("ni un retorno de carro: lo generado y lo guardado tienen que coincidir byte a byte", () => {
    expect(avisos.includes("\r")).toBe(false);
    expect(generador).toContain('replace(/\\r\\n?/g, "\\n")');
  });
});
