import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { resolveVersions } from "./npm-lockfiles";

/**
 * The npm family's locks, against real files.
 *
 * These fragments are not handwritten: they come from running `yarn@1.22.22 install` and
 * `yarn@4.5.0 install` on a `package.json` set up so that every rare case would appear, and from a
 * public `bun.lock` of 512 packets. Making up the format is exactly how you write a reader that
 * passes its tests and fails on the first real disk.
 *
 * What is being defended here is a single thing, and it is what is needed to inquire about
 * security advisories: **the name exactly as declared by manifest, with the version that is
 * actually installed**. A name that does not match is a package that is never checked; a version
 * from another branch is an advisory that is either made up or lost. Both, in silence.
 */
let home: string;

beforeAll(async () => {
  home = await mkdtemp(join(tmpdir(), "panoma-candados-"));
});

afterAll(async () => {
  await rm(home, { recursive: true, force: true });
});

/** Put a lockfile in a folder and read it there, just as the scanner does. */
async function resolve(
  file: string,
  content: string,
  declared?: Record<string, string>,
): Promise<Map<string, string> | undefined> {
  const root = await mkdtemp(join(home, "proyecto-"));
  await writeFile(join(root, file), content, "utf8");
  return resolveVersions(root, file, declared ? new Map(Object.entries(declared)) : undefined);
}

describe("yarn.lock del clásico (Yarn 1)", () => {
  /* Generado con `npx yarn@1.22.22 install`. */
  const REAL = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@sindresorhus/is@^5.6.0":
  version "5.6.0"
  resolved "https://registry.yarnpkg.com/@sindresorhus/is/-/is-5.6.0.tgz#41dd6093"

"alias-picocolors@npm:picocolors@^1.0.0":
  version "1.1.1"
  resolved "https://registry.yarnpkg.com/picocolors/-/picocolors-1.1.1.tgz#3d321af3"

ansi-styles@^4.1.0:
  version "4.3.0"
  dependencies:
    color-convert "^2.0.1"

body-parser@^1.20.0, body-parser@~1.20.5:
  version "1.20.5"
`;

  it("saca nombre y versión de cada entrada", async () => {
    const versions = await resolve("yarn.lock", REAL);
    expect(versions?.get("ansi-styles")).toBe("4.3.0");
    expect(versions?.get("body-parser")).toBe("1.20.5");
  });

  it("un paquete con ámbito no se parte por la arroba de su ámbito", async () => {
    expect((await resolve("yarn.lock", REAL))?.get("@sindresorhus/is")).toBe("5.6.0");
  });

  /*
    The case that knocks down a reader who cuts at the last at sign.
    The manifest declares `"alias-picocolors": "npm:picocolors@^1.0.0"`. The name to return is the
    one it declared: returning `picocolors` would leave the alias unchecked **and** would assign
    `picocolors` a version that this project does not declare.
   */
  it("un alias devuelve el nombre del manifiesto, no el del paquete de detrás", async () => {
    const versions = await resolve("yarn.lock", REAL);
    expect(versions?.get("alias-picocolors")).toBe("1.1.1");
    expect(versions?.has("picocolors"), "el paquete de detrás no es lo que se declaró").toBe(false);
  });

  /*
    `version` is a package that exists on npm. If an entry depends on it, its dependency block
    brings a line with four spaces that looks dangerously like the version of the entry, which
    goes with two. That is why the indentation looks exact.
   */
  it("no confunde una dependencia llamada «version» con la versión de la entrada", async () => {
    const versions = await resolve(
      "yarn.lock",
      `algo@^1.0.0:
  version "3.3.3"
  dependencies:
    version "^1.0.0"
`,
    );
    expect(versions?.get("algo")).toBe("3.3.3");
  });

  /*
    The file is sorted **alphabetically by descriptor**, not by depth. When a package appears
    twice —once because it is requested by the project and once because it is requested by another
    dependency— keeping "the first" returns the transitive one. Measured in public projects:
    between 5% and 14% of the direct ones came out with the version of another.
    The tiebreaker doesn’t need to compare numbers: Yarn writes the range exactly as manifest put
    it, so it’s enough to know which one the project requested.
   */
  it("con dos ramas del mismo paquete, gana la que pidió el manifiesto", async () => {
    const dosRamas = `semver@^6.3.1:
  version "6.3.1"

semver@^7.5.0:
  version "7.8.5"
`;
    expect((await resolve("yarn.lock", dosRamas))?.get("semver"), "sin saber qué se pidió, la primera").toBe("6.3.1");
    expect(
      (await resolve("yarn.lock", dosRamas, { semver: "^7.5.0" }))?.get("semver"),
      "sabiéndolo, la que el proyecto declaró",
    ).toBe("7.8.5");
  });

  /*
    Up to Yarn 1.21, the entries were grouped by resolved URL and not by name, so a group can name
    **different packages**. Keeping only the first descriptor loses the others — and here `lodash`
    is lost, which in 4.17.20 carries a real warning: the project would come out clean because of
    the exact failure that this file exists to prevent.
   */
  it("un grupo puede nombrar varios paquetes, y entran todos", async () => {
    const versions = await resolve(
      "yarn.lock",
      `"lodash-alias@npm:lodash@4.17.20", lodash@4.17.20, "otro-alias@npm:lodash@4.17.20":
  version "4.17.20"
`,
    );
    expect(versions?.get("lodash")).toBe("4.17.20");
    expect(versions?.get("lodash-alias")).toBe("4.17.20");
    expect(versions?.get("otro-alias")).toBe("4.17.20");
  });

  /* A URL from git can have commas inside its quotes: split manually invent a package. */
  it("una coma dentro de comillas no parte un descriptor", async () => {
    const versions = await resolve(
      "yarn.lock",
      `"x@git+https://ej.com/r.git?a=1,b=u@v#v3", x@^9.0.0:
  version "3.0.0"
`,
    );
    expect(versions?.get("x")).toBe("3.0.0");
    expect(versions?.has("b=u"), "«b=u» no es un paquete").toBe(false);
  });
});

describe("yarn.lock de berry (Yarn 2 en adelante)", () => {
  /* Generado con `corepack yarn@4.5.0 install --mode=update-lockfile`. */
  const REAL = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"@sindresorhus/is@npm:^5.6.0":
  version: 5.6.0
  resolution: "@sindresorhus/is@npm:5.6.0"
  languageName: node
  linkType: hard

"alias-picocolors@npm:picocolors@^1.0.0":
  version: 1.1.1
  resolution: "picocolors@npm:1.1.1"
  languageName: node
  linkType: hard

"chalk@npm:^2.4.2":
  version: 2.4.2
  resolution: "chalk@npm:2.4.2"
  languageName: node
  linkType: hard

"chalk@npm:^4.1.2":
  version: 4.1.2
  resolution: "chalk@npm:4.1.2"
  languageName: node
  linkType: hard

"prueba-berry@workspace:.":
  version: 0.0.0-use.local
  resolution: "prueba-berry@workspace:."
  dependencies:
    "@sindresorhus/is": "npm:^5.6.0"
    alias-picocolors: "npm:picocolors@^1.0.0"
    chalk: "npm:^4.1.2"
  languageName: unknown
  linkType: soft
`;

  it("lee las versiones de lo que el proyecto pide", async () => {
    const versions = await resolve("yarn.lock", REAL);
    expect(versions?.get("@sindresorhus/is")).toBe("5.6.0");
  });

  /*
    The reason why the names DO NOT come from breaking down the keys and the versions are resolved
    by descriptor: `chalk@npm:^2.4.2` comes before `chalk@npm:^4.1.2` in the alphabet, and the
    project requests number 4. On a public lock with 2120 keys, resolving alphabetically changed
    129 versions.
   */
  it("con dos ramas del mismo paquete, gana la que el proyecto pide, no la primera", async () => {
    expect((await resolve("yarn.lock", REAL))?.get("chalk")).toBe("4.1.2");
  });

  it("no toma `__metadata` por un paquete, aunque tenga un campo «version»", async () => {
    const versions = await resolve("yarn.lock", REAL);
    expect(versions?.has("__metadata")).toBe(false);
    expect([...(versions?.values() ?? [])], "el 8 de __metadata no es la versión de nada").not.toContain("8");
  });

  it("ni el propio proyecto, que se anota como workspace", async () => {
    expect((await resolve("yarn.lock", REAL))?.has("prueba-berry")).toBe(false);
  });

  it("en un alias usa el nombre que se declaró, no el paquete de detrás", async () => {
    const versions = await resolve("yarn.lock", REAL);
    expect(versions?.get("alias-picocolors")).toBe("1.1.1");
    expect(versions?.has("picocolors")).toBe(false);
  });

  /*
    A `yarn.lock` from Yarn 1 **parses as YAML without throwing**: it returns good keys with
    values that are a single string. Without distinguishing the raw text before parsing, a Yarn 1
    project would come out with zero packages and no error — that is, "0 vulnerabilities" without
    looking at it.
   */
  it("un fichero de Yarn 1 no se cuela por aquí", async () => {
    const versions = await resolve("yarn.lock", `chalk@^4.1.2:\n  version "4.1.2"\n`);
    expect(versions?.get("chalk"), "lo lee el lector clásico, no el de berry").toBe("4.1.2");
  });

  /*
    The filename of a patch is chosen by whoever creates it, and Yarn writes it without escaping
    the commas. Splitting the key would put `react → 1.3.0` in a project that has React 18.
   */
  it("una coma dentro de una clave de parche no inventa un paquete", async () => {
    const versions = await resolve(
      "yarn.lock",
      `__metadata:
  version: 8

"left-pad@patch:left-pad@npm%3A1.3.0#~/.yarn/patches/left-pad,react@18.patch":
  version: 1.3.0
  languageName: node

"react@npm:^18.3.1":
  version: 18.3.1
  resolution: "react@npm:18.3.1"
  languageName: node

"app@workspace:.":
  version: 0.0.0-use.local
  dependencies:
    react: "npm:^18.3.1"
  languageName: unknown
`,
    );
    expect(versions?.get("react"), "la que está instalada, no la del parche").toBe("18.3.1");
  });
});

describe("bun.lock, el candado en texto de Bun 1.2 en adelante", () => {
  /* Clipped from a real `bun.lock` of 512 packets: thisuxhq/sveltednd on GitHub. */
  const REAL = `{
  "lockfileVersion": 1,
  "workspaces": {
    "": { "name": "@thisux/sveltednd", "devDependencies": { "svelte": "^5.55.1" } }
  },
  "packages": {
    "@alloc/quick-lru": ["@alloc/quick-lru@5.2.0", "", {}, "sha512-UrcABB"],

    "svelte": ["svelte@5.55.1", "", { "dependencies": { "acorn": "^8.15.0" } }, "sha512-9NhCe"],

    "minimist": ["minimist@1.2.8", "", {}, "sha512-2yyAR8"],

    "bbb-second/minimist": ["minimist@1.2.5", "", {}, "sha512-FM9nNU"],

    "app": ["app@workspace:packages/app"],
  }
}
`;

  it("lee el JSONC, que JSON.parse rechaza por las comas finales", async () => {
    expect((await resolve("bun.lock", REAL))?.get("svelte")).toBe("5.55.1");
  });

  it("un ámbito lleva barra y no es un anidamiento", async () => {
    expect((await resolve("bun.lock", REAL))?.get("@alloc/quick-lru")).toBe("5.2.0");
  });

  /*
    Bun annotates each nested copy with the full path by key. The good name is the last segment
    —`bbb-second/minimist` is the minimist that sees `bbb-second` — and when the same package is
    there twice, the level 0 one wins. What really matters here: 1.2.5 has a warning and 1.2.8
    does not.
   */
  it("de dos copias del mismo paquete gana la de nivel 0", async () => {
    const versions = await resolve("bun.lock", REAL);
    expect(versions?.get("minimist")).toBe("1.2.8");
    expect(versions?.has("bbb-second/minimist"), "la ruta no es un nombre de paquete").toBe(false);
  });

  it("un miembro del workspace no es un paquete del registro", async () => {
    expect((await resolve("bun.lock", REAL))?.has("app")).toBe(false);
  });

  /*
    In an alias the key names what manifest declared and the descriptor the real package. That
    pair does not exist in any record: truly asked, `my-lodash@4.17.20` returns zero notices and
    `lodash@4.17.20` returns five. The row is discarded, which is the honest minimum.
   */
  it("un alias se descarta en vez de contestar que está limpio", async () => {
    const versions = await resolve(
      "bun.lock",
      `{ "packages": { "my-lodash": ["lodash@4.17.20", "", {}, "sha512-Plhd"] } }`,
    );
    expect(versions?.has("my-lodash")).toBe(false);
    expect(versions?.has("lodash"), "tampoco el de detrás: el proyecto no lo declara así").toBe(false);
  });

  it("una preliberación sí es una versión", async () => {
    const versions = await resolve(
      "bun.lock",
      `{ "packages": { "algo": ["algo@1.0.0-beta.3", "", {}, "sha512-x"] } }`,
    );
    expect(versions?.get("algo")).toBe("1.0.0-beta.3");
  });
});

describe("leer un fichero y no encontrar nada no es lo mismo que no poder leerlo", () => {
  /*
    It is the distinction on which everything hangs. `undefined` turns on `lockUnresolved`, and
    with that the screen writes "without checking." A project without dependencies has a perfectly
    readable lockfile and would appear in yellow accusing Panoma of not knowing how to read it.
   */
  it("un candado sin paquetes devuelve un mapa vacío", async () => {
    expect((await resolve("yarn.lock", "# yarn lockfile v1\n\n"))?.size).toBe(0);
    expect((await resolve("bun.lock", `{ "lockfileVersion": 1, "packages": {} }`))?.size).toBe(0);
  });

  it("y `packages` ausente también, que Bun lee como vacío", async () => {
    expect((await resolve("bun.lock", `{ "lockfileVersion": 1 }`))?.size).toBe(0);
  });

  it("`bun.lockb` es binario y devuelve undefined, no un cero", async () => {
    expect(await resolve("bun.lockb", " binario ")).toBeUndefined();
  });

  it("un candado que no existe también", async () => {
    const root = await mkdtemp(join(home, "vacio-"));
    expect(await resolveVersions(root, "yarn.lock")).toBeUndefined();
  });
});
